apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.20.0
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/environments/lab/helm/cert-manager/values.yaml
    - repoURL: git@github.com:ednillibanio/talos-vsphere-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
