#!/usr/bin/env bash
set -euo pipefail

# validate-values-overrides.sh
#
# Offline check that every addon's values file under a Helm root is a small,
# owned override set rather than a vendored copy of the chart's own default
# values.yaml. For each addon directory it asserts the values file exists,
# does not carry a chart-generated vendoring marker, and does not sit next to
# a leftover values.base.yaml. When `helm` is installed it also pulls the
# chart pinned in release.yaml (network access, no cluster/credentials) and
# renders it with the values file.
#
# A chart pinned by classic repo alias (`longhorn/longhorn`) is resolved by
# reading the matching Argo CD Application's repoURL and passing it to
# `helm pull --repo`, so the check does not depend on which aliases happen to
# be registered in the caller's Helm config and never mutates it.
#
# A pinned chart that cannot be resolved or rendered is a failure. It used to
# be reported as a note while the script still exited zero, which let a green
# run silently skip an addon.
#
# This is the addon-agnostic counterpart to
# validate-cilium-values-overrides.sh, which additionally enforces Cilium's
# documented set of required override keys. Run both.
#
# Contacts no Kubernetes, Argo CD, Docker, Colima, Talos, or VMware endpoint
# and uses no credentials.
#
# Usage: validate-values-overrides.sh [helm-root]
#
# Actions:
#   (default) Validate every addon under environments/lab/helm
#
# Options:
#   -h, --help   Show this help and exit
#
# Examples:
#   ./scripts/validate-values-overrides.sh
#   ./scripts/validate-values-overrides.sh environments/lab/helm

usage() {
  sed -n '2,32p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

helm_root="${1:-environments/lab/helm}"
fail=0

if [[ ! -d "$helm_root" ]]; then
  echo "error: helm root not found: $helm_root" >&2
  exit 2
fi

# Markers that identify a values file copied wholesale from a chart, rather
# than written as an override set. Each is a header the upstream charts ship
# in their own default values.yaml.
vendored_markers=(
  'generated by install/kubernetes/Makefile'
  '+docs:section='
  'Default values for'
)

addon_count=0

for addon_dir in "$helm_root"/*/; do
  [[ -d "$addon_dir" ]] || continue
  addon="$(basename "$addon_dir")"
  values_file="${addon_dir}values.yaml"
  release_file="${addon_dir}release.yaml"
  addon_count=$((addon_count + 1))

  if [[ ! -f "$values_file" ]]; then
    echo "FAIL: $addon: values file not found: $values_file" >&2
    fail=1
    continue
  fi

  for marker in "${vendored_markers[@]}"; do
    if grep -qF "$marker" "$values_file"; then
      echo "FAIL: $addon: $values_file carries a chart vendoring marker: $marker" >&2
      fail=1
    fi
  done

  vendored_default_file="${addon_dir}values.base.yaml"
  if [[ -f "$vendored_default_file" ]]; then
    echo "FAIL: $addon: unreferenced vendored defaults still present: $vendored_default_file" >&2
    fail=1
  fi
done

if [[ "$addon_count" -eq 0 ]]; then
  echo "error: no addon directories found under $helm_root" >&2
  exit 2
fi

if [[ "$fail" -ne 0 ]]; then
  echo "FAIL: values override contract violations detected" >&2
  exit 1
fi

echo "OK: all $addon_count addon values files under $helm_root are minimal owned override sets"

if ! command -v helm >/dev/null 2>&1; then
  echo "note: helm not installed; skipping pinned-chart renders" >&2
  exit 0
fi

# --- pinned-chart render, per addon -----------------------------------------

# Argo CD Applications sit beside the Helm root and carry the real chart
# repository URL for charts that release.yaml pins by alias.
apps_dir="$(dirname "$helm_root")/argocd/apps"

# Print the repoURL of the source that serves $2 in Application file $1.
# In these manifests the chart source is a repoURL line followed by its chart
# line, so the last repoURL seen before the matching chart is the right one.
chart_repo_url() {
  local app_file="$1" chart_name="$2"
  [[ -f "$app_file" ]] || return 1
  awk -v want="$chart_name" '
    /^[[:space:]]*-?[[:space:]]*repoURL:[[:space:]]*/ {
      url = $0; sub(/^[^:]*:[[:space:]]*/, "", url)
    }
    /^[[:space:]]*chart:[[:space:]]*/ {
      c = $0; sub(/^[[:space:]]*chart:[[:space:]]*/, "", c)
      if (c == want && url != "") { print url; exit }
    }
  ' "$app_file"
}

for addon_dir in "$helm_root"/*/; do
  [[ -d "$addon_dir" ]] || continue
  addon="$(basename "$addon_dir")"
  values_file="${addon_dir}values.yaml"
  release_file="${addon_dir}release.yaml"

  if [[ ! -f "$release_file" ]]; then
    echo "note: $addon: release file not found ($release_file); skipping render" >&2
    continue
  fi

  chart="$(sed -n 's/^chart:[[:space:]]*//p' "$release_file" | head -n1)"
  version="$(sed -n 's/^version:[[:space:]]*//p' "$release_file" | head -n1)"
  namespace="$(sed -n 's/^namespace:[[:space:]]*//p' "$release_file" | head -n1)"

  if [[ -z "$chart" || -z "$version" ]]; then
    echo "FAIL: $addon: could not parse chart/version from $release_file" >&2
    fail=1
    continue
  fi

  # A chart pinned as alias/name resolves through the Application's repoURL
  # when one is available, so no Helm repo alias has to be registered locally.
  pull_args=("$chart")
  if [[ "$chart" != *"://"* && "$chart" == */* ]]; then
    chart_name="${chart#*/}"
    repo_url="$(chart_repo_url "$apps_dir/$addon.yaml" "$chart_name" || true)"
    if [[ -n "$repo_url" ]]; then
      pull_args=("$chart_name" --repo "$repo_url")
    fi
  fi

  chart_dir="$(mktemp -d)"
  pull_out="$(mktemp)"
  render_out="$(mktemp)"

  if ! helm pull "${pull_args[@]}" --version "$version" --destination "$chart_dir" \
    >"$pull_out" 2>&1; then
    echo "FAIL: $addon: could not resolve pinned chart $chart:$version" >&2
    cat "$pull_out" >&2
    fail=1
    rm -rf "$chart_dir"; rm -f "$pull_out" "$render_out"
    continue
  fi

  chart_archive="$(find "$chart_dir" -maxdepth 1 -name '*.tgz' | head -n1)"
  if [[ -z "$chart_archive" ]]; then
    echo "FAIL: $addon: helm pull produced no archive for $chart:$version" >&2
    fail=1
    rm -rf "$chart_dir"; rm -f "$pull_out" "$render_out"
    continue
  fi

  if helm template "values-check-$addon" "$chart_archive" \
    --namespace "${namespace:-default}" -f "$values_file" >"$render_out" 2>&1; then
    echo "OK: $addon: helm template rendered $values_file against $chart:$version"
  else
    echo "FAIL: $addon: resolved chart $chart:$version could not render $values_file" >&2
    cat "$render_out" >&2
    fail=1
  fi

  rm -rf "$chart_dir"; rm -f "$pull_out" "$render_out"
done

exit "$fail"
