#!/usr/bin/env bash
set -euo pipefail

# validate-values-overrides.sh
#
# Offline check that every addon's values file under a Helm root is a small,
# owned override set rather than a vendored copy of the chart's own default
# values.yaml. For each addon directory it asserts the values file exists,
# does not carry a chart-generated vendoring marker, and does not sit next to
# a leftover values.base.yaml. When `helm` is installed it also pulls the
# chart pinned in release.yaml (network access, no cluster/credentials) and
# renders it with the values file. A chart that cannot be pulled/resolved is
# reported as a limitation, not a failure. A resolved chart that fails to
# render with the supplied values is a real validation failure.
#
# This is the addon-agnostic counterpart to
# validate-cilium-values-overrides.sh, which additionally enforces Cilium's
# documented set of required override keys. Run both.
#
# Contacts no Kubernetes, Argo CD, Docker, Colima, Talos, or VMware endpoint
# and uses no credentials.
#
# Usage: validate-values-overrides.sh [helm-root]
#
# Actions:
#   (default) Validate every addon under environments/lab/helm
#
# Options:
#   -h, --help   Show this help and exit
#
# Examples:
#   ./scripts/validate-values-overrides.sh
#   ./scripts/validate-values-overrides.sh environments/lab/helm

usage() {
  sed -n '2,32p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

helm_root="${1:-environments/lab/helm}"
fail=0

if [[ ! -d "$helm_root" ]]; then
  echo "error: helm root not found: $helm_root" >&2
  exit 2
fi

# Markers that identify a values file copied wholesale from a chart, rather
# than written as an override set. Each is a header the upstream charts ship
# in their own default values.yaml.
vendored_markers=(
  'generated by install/kubernetes/Makefile'
  '+docs:section='
  'Default values for'
)

addon_count=0

for addon_dir in "$helm_root"/*/; do
  [[ -d "$addon_dir" ]] || continue
  addon="$(basename "$addon_dir")"
  values_file="${addon_dir}values.yaml"
  release_file="${addon_dir}release.yaml"
  addon_count=$((addon_count + 1))

  if [[ ! -f "$values_file" ]]; then
    echo "FAIL: $addon: values file not found: $values_file" >&2
    fail=1
    continue
  fi

  for marker in "${vendored_markers[@]}"; do
    if grep -qF "$marker" "$values_file"; then
      echo "FAIL: $addon: $values_file carries a chart vendoring marker: $marker" >&2
      fail=1
    fi
  done

  vendored_default_file="${addon_dir}values.base.yaml"
  if [[ -f "$vendored_default_file" ]]; then
    echo "FAIL: $addon: unreferenced vendored defaults still present: $vendored_default_file" >&2
    fail=1
  fi
done

if [[ "$addon_count" -eq 0 ]]; then
  echo "error: no addon directories found under $helm_root" >&2
  exit 2
fi

if [[ "$fail" -ne 0 ]]; then
  echo "FAIL: values override contract violations detected" >&2
  exit 1
fi

echo "OK: all $addon_count addon values files under $helm_root are minimal owned override sets"

if ! command -v helm >/dev/null 2>&1; then
  echo "note: helm not installed; skipping pinned-chart renders" >&2
  exit 0
fi

# --- pinned-chart render, per addon -----------------------------------------

for addon_dir in "$helm_root"/*/; do
  [[ -d "$addon_dir" ]] || continue
  addon="$(basename "$addon_dir")"
  values_file="${addon_dir}values.yaml"
  release_file="${addon_dir}release.yaml"

  if [[ ! -f "$release_file" ]]; then
    echo "note: $addon: release file not found ($release_file); skipping render" >&2
    continue
  fi

  chart="$(sed -n 's/^chart:[[:space:]]*//p' "$release_file" | head -n1)"
  version="$(sed -n 's/^version:[[:space:]]*//p' "$release_file" | head -n1)"
  namespace="$(sed -n 's/^namespace:[[:space:]]*//p' "$release_file" | head -n1)"

  if [[ -z "$chart" || -z "$version" ]]; then
    echo "note: $addon: could not parse chart/version from $release_file; skipping render" >&2
    continue
  fi

  chart_dir="$(mktemp -d)"
  pull_out="$(mktemp)"
  render_out="$(mktemp)"

  if ! helm pull "$chart" --version "$version" --destination "$chart_dir" \
    >"$pull_out" 2>&1; then
    echo "note: $addon: pinned chart $chart:$version was not locally resolvable; reporting limitation instead of substituting a live-cluster check" >&2
    rm -rf "$chart_dir"; rm -f "$pull_out" "$render_out"
    continue
  fi

  chart_archive="$(find "$chart_dir" -maxdepth 1 -name '*.tgz' | head -n1)"
  if [[ -z "$chart_archive" ]]; then
    echo "note: $addon: pinned chart was not locally resolvable (helm pull produced no archive)" >&2
    rm -rf "$chart_dir"; rm -f "$pull_out" "$render_out"
    continue
  fi

  if helm template "values-check-$addon" "$chart_archive" \
    --namespace "${namespace:-default}" -f "$values_file" >"$render_out" 2>&1; then
    echo "OK: $addon: helm template rendered $values_file against $chart:$version"
  else
    echo "FAIL: $addon: resolved chart $chart:$version could not render $values_file" >&2
    cat "$render_out" >&2
    fail=1
  fi

  rm -rf "$chart_dir"; rm -f "$pull_out" "$render_out"
done

exit "$fail"
