#!/usr/bin/env bash
set -euo pipefail

# validate-cilium-values-overrides.sh
#
# Offline check that an environment's Cilium values file is a small, owned
# override set rather than a vendored copy of the chart's own default
# values.yaml: it must exist, must not carry the chart's generated "DO NOT
# EDIT" marker, must declare every documented owned-override key, and must
# not sit next to a vendored values.base.yaml. When `helm` is installed, the
# script also pulls the pinned chart from its OCI registry (network access,
# no cluster/credentials) and, once that chart is locally resolved, renders
# it with the values file. A chart that cannot be pulled/resolved is reported
# as a limitation, not a failure. A resolved chart that fails to render with
# the supplied values is a real validation failure and exits non-zero.
# Contacts no Kubernetes, Argo CD, Docker, Colima, Talos, or VMware endpoint
# and uses no credentials.
#
# Usage: validate-cilium-values-overrides.sh [values-file] [release-file]
#
# Actions:
#   (default) Validate environments/lab/helm/cilium/values.yaml against
#             environments/lab/helm/cilium/release.yaml
#
# Options:
#   -h, --help   Show this help and exit
#
# Examples:
#   ./scripts/validate-cilium-values-overrides.sh
#   ./scripts/validate-cilium-values-overrides.sh \
#     scripts/testdata/cilium-values/valid/values.yaml \
#     scripts/testdata/cilium-values/valid/release.yaml

usage() {
  sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

values_file="${1:-environments/lab/helm/cilium/values.yaml}"
release_file="${2:-environments/lab/helm/cilium/release.yaml}"
fail=0

required_keys=(
  k8sServiceHost
  k8sServicePort
  securityContext
  ingressController
  gatewayAPI
  encryption
  ipam
  kubeProxyReplacement
  cgroup
)

if [[ ! -f "$values_file" ]]; then
  echo "error: values file not found: $values_file" >&2
  exit 2
fi

vendored_marker='generated by install/kubernetes/Makefile'
if grep -qi "$vendored_marker" "$values_file"; then
  echo "FAIL: $values_file still carries the chart-generated vendoring marker" >&2
  fail=1
fi

for key in "${required_keys[@]}"; do
  if ! grep -qE "^${key}:" "$values_file"; then
    echo "FAIL: $values_file missing documented owned-override key: $key" >&2
    fail=1
  fi
done

vendored_default_file="$(dirname "$values_file")/values.base.yaml"
if [[ -f "$vendored_default_file" ]]; then
  echo "FAIL: unreferenced vendored defaults still present: $vendored_default_file" >&2
  fail=1
fi

if [[ "$fail" -ne 0 ]]; then
  echo "FAIL: Cilium values override contract violations detected" >&2
  exit 1
fi

echo "OK: $values_file is a minimal owned override set"

if [[ ! -f "$release_file" ]]; then
  echo "note: release file not found ($release_file); skipping pinned-chart Helm render" >&2
  exit 0
fi

chart="$(sed -n 's/^chart:[[:space:]]*//p' "$release_file" | head -n1)"
version="$(sed -n 's/^version:[[:space:]]*//p' "$release_file" | head -n1)"

if [[ -z "$chart" || -z "$version" ]]; then
  echo "note: could not parse chart/version from $release_file; skipping pinned-chart Helm render" >&2
  exit 0
fi

if ! command -v helm >/dev/null 2>&1; then
  echo "note: helm not installed; skipping pinned-chart Helm render (chart=$chart version=$version)" >&2
  exit 0
fi

pull_out="$(mktemp)"
render_out="$(mktemp)"
chart_dir="$(mktemp -d)"
trap 'rm -f "$pull_out" "$render_out"; rm -rf "$chart_dir"' EXIT

if ! helm pull "$chart" --version "$version" --destination "$chart_dir" \
  >"$pull_out" 2>&1; then
  echo "note: pinned Cilium chart was not locally resolvable; reporting limitation instead of substituting a live-cluster check" >&2
  echo "note: helm pull output follows" >&2
  cat "$pull_out" >&2
  exit 0
fi

chart_archive="$(find "$chart_dir" -maxdepth 1 -name '*.tgz' | head -n1)"
if [[ -z "$chart_archive" ]]; then
  echo "note: pinned Cilium chart was not locally resolvable (helm pull produced no archive); reporting limitation instead of substituting a live-cluster check" >&2
  exit 0
fi

if helm template cilium-values-check "$chart_archive" \
  --namespace kube-system -f "$values_file" >"$render_out" 2>&1; then
  echo "OK: helm template rendered $values_file against $chart:$version"
else
  echo "FAIL: resolved chart $chart:$version could not render $values_file" >&2
  echo "FAIL: helm template output follows" >&2
  cat "$render_out" >&2
  exit 1
fi
